"""Step 3 — pen paths into G-code.

IMPORTANT: the pen up/down commands depend on YOUR firmware. The defaults here
are the GRBL-with-servo convention (M3/M5). If your ESP32 sketch uses something
else, change PEN_UP_CMD / PEN_DOWN_CMD -- they are environment variables, so you
do not have to touch the code.

Common alternatives:
    M280 P0 S30  /  M280 P0 S90     (Marlin, servo on the probe pin)
    M3 S0        /  M3 S255          (GRBL with a servo on PWM)
    SERVO 30     /  SERVO 90         (home-grown firmware)
"""

import os

import numpy as np

PEN_UP_CMD = os.environ.get("PEN_UP_CMD", "M5")
PEN_DOWN_CMD = os.environ.get("PEN_DOWN_CMD", "M3 S255")

# How long the servo needs to raise or lower the pen. Without this pause the
# plotter starts moving while the pen is still in the air and the beginning of
# every stroke comes out clipped.
PEN_DELAY_MS = int(os.environ.get("PEN_DELAY_MS", "250"))


def fit_to_bed(paths, img_shape, bed_w=100.0, bed_h=100.0, margin=5.0):
    """Scale polylines from pixel coordinates to millimetres.

    Two things it does that are easy to forget:
      1. Keeps the aspect ratio (one scale factor, not one per axis), otherwise
         the portrait comes out stretched.
      2. Flips the Y axis. In an image row 0 is at the TOP; on the plotter Y=0
         is at the BOTTOM. Without this flip the drawing comes out upside down.
    """
    img_h, img_w = img_shape
    usable_w = bed_w - 2 * margin
    usable_h = bed_h - 2 * margin
    if usable_w <= 0 or usable_h <= 0:
        raise ValueError("margin leaves no usable area; lower margin or raise bed size")

    scale = min(usable_w / img_w, usable_h / img_h)

    # Centre whatever slack is left on the roomier axis.
    off_x = margin + (usable_w - img_w * scale) / 2.0
    off_y = margin + (usable_h - img_h * scale) / 2.0

    out = []
    for p in paths:
        p = np.asarray(p, dtype=np.float64)
        y, x = p[:, 0], p[:, 1]
        mm = np.empty_like(p)
        mm[:, 0] = x * scale + off_x
        mm[:, 1] = (img_h - 1 - y) * scale + off_y  # <- the Y flip
        out.append(mm)

    return out


def generate(paths_mm, *, feed_draw=1200, feed_travel=3000, bed_w=100.0, bed_h=100.0):
    """Emit the G-code plus some useful stats. Returns (gcode_text, stats).

    Everything is keyword-only on purpose. With positional arguments,
    generate(paths, 100, 100) reads like "a 100x100 bed" but actually sets the
    feed rates to 100 mm/min, and the only symptom is an estimated time 7x too
    high -- every other stat stays identical, so it is very easy to miss.
    """
    lines = [
        "; ---------------------------------------------",
        "; Generated by photo-to-plot",
        f"; Drawing area: {bed_w:.1f} x {bed_h:.1f} mm",
        f"; Strokes: {len(paths_mm)}",
        "; ---------------------------------------------",
        "G21",           # millimetres
        "G90",           # absolute coordinates
        PEN_UP_CMD,      # ALWAYS start with the pen up
        f"G4 P{PEN_DELAY_MS}",
        "G0 X0 Y0",      # home before starting
    ]

    draw_dist = 0.0
    travel_dist = 0.0
    cur = np.array([0.0, 0.0])

    for path in paths_mm:
        if len(path) < 2:
            continue

        # Travel through the air to the start of the stroke.
        travel_dist += float(np.hypot(*(path[0] - cur)))
        lines.append(f"G0 X{path[0][0]:.3f} Y{path[0][1]:.3f} F{feed_travel}")

        lines.append(PEN_DOWN_CMD)
        lines.append(f"G4 P{PEN_DELAY_MS}")

        for pt in path[1:]:
            lines.append(f"G1 X{pt[0]:.3f} Y{pt[1]:.3f} F{feed_draw}")

        draw_dist += float(np.sum(np.hypot(np.diff(path[:, 0]), np.diff(path[:, 1]))))

        lines.append(PEN_UP_CMD)
        lines.append(f"G4 P{PEN_DELAY_MS}")
        cur = path[-1]

    lines += [
        "G0 X0 Y0",
        PEN_UP_CMD,
        "; end",
    ]

    # Time estimate: distance/speed plus the servo going up and down. It ignores
    # acceleration, so in practice it runs a little optimistic.
    secs = (draw_dist / feed_draw + travel_dist / feed_travel) * 60.0
    secs += len(paths_mm) * 2 * (PEN_DELAY_MS / 1000.0)

    stats = {
        "paths": len(paths_mm),
        "points": int(sum(len(p) for p in paths_mm)),
        "draw_mm": round(draw_dist, 1),
        "travel_mm": round(travel_dist, 1),
        "gcode_lines": len(lines),
        "estimated_seconds": int(secs),
    }

    return "\n".join(lines) + "\n", stats


def to_svg(paths_mm, bed_w=100.0, bed_h=100.0):
    """SVG preview: exactly the paths the pen will follow. Open it in a browser
    BEFORE sending anything to the plotter."""
    out = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{bed_w}mm" height="{bed_h}mm" '
        f'viewBox="0 0 {bed_w} {bed_h}">',
        f'<rect width="{bed_w}" height="{bed_h}" fill="white"/>',
    ]
    for p in paths_mm:
        # SVG has Y pointing down, same as the image, so we undo the flip we did
        # for the plotter.
        pts = " ".join(f"{x:.2f},{bed_h - y:.2f}" for x, y in p)
        out.append(
            f'<polyline points="{pts}" fill="none" stroke="black" '
            f'stroke-width="0.3" stroke-linecap="round" stroke-linejoin="round"/>'
        )
    out.append("</svg>")
    return "\n".join(out)
